export const GET_ALL_USERS = "GET_ALL_USERS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const USER_IS_TAKEN = "USER_IS_TAKEN";
export const GET_TASKS_BY_USER = "GET_TASKS_BY_USER";
export const ADD_TASK = "ADD_TASK";
export const COMPLETED_TASK = "COMPLETED_TASK";
export const CLEAR_ALL_COMPLETED = "CLEAR_ALL_COMPLETED";
export const CLOSE_TASK = "CLOSE_TASK";
export const FILTERED_BY_COMPLETED = "FILTERED_BY_COMPLETED";
export const FILTERED_BY_ACTIVES = "FILTERED_BY_ACTIVES";
export const LOGOUT = "LOGOUT";
export const UPDATE_TASKS_ORDER = 'UPDATE_TASKS_ORDER';

