export const GET_ALL_USERS = "GET_ALL_USERS";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const USER_IS_TAKEN = "USER_IS_TAKEN";
